import { build } from "esbuild";
import * as fs from "fs";
import * as path from "path";

const production = process.argv[2] === "production";
const PLUGIN_ID = "mkortex-updater";
const DIST_DIR = path.join("dist", PLUGIN_ID);
const VAULT_PLUGIN_DIR = `/Users/kazakovvladimir/Documents/MKRobotsAI/.obsidian/plugins/${PLUGIN_ID}`;
const ARTIFACTS = ["main.js", "manifest.json", "styles.css"];

function copyArtifacts(targetDir, { includeSourcemap = false } = {}) {
  fs.mkdirSync(targetDir, { recursive: true });
  for (const file of ARTIFACTS) {
    if (!fs.existsSync(file)) {
      throw new Error(`Missing build artifact: ${file}`);
    }
    fs.copyFileSync(file, path.join(targetDir, file));
  }
  if (includeSourcemap && fs.existsSync("main.js.map")) {
    fs.copyFileSync("main.js.map", path.join(targetDir, "main.js.map"));
  }
}

async function main() {
  await build({
    entryPoints: ["src/main.ts"],
    bundle: true,
    minify: production,
    sourcemap: !production,
    outfile: "main.js",
    external: ["obsidian"],
    format: "cjs",
    platform: "node",
    banner: {
      js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */",
    },
  });

  copyArtifacts(DIST_DIR, { includeSourcemap: false });
  copyArtifacts(VAULT_PLUGIN_DIR, { includeSourcemap: !production });

  console.log(`✓ Build ${production ? "(production)" : "(dev)"} complete`);
  console.log(`✓ Dist: ${DIST_DIR}`);
  console.log(`✓ Copied to vault: ${VAULT_PLUGIN_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
